### ISSUE TITLE
Warnig emitted for System.Windows.Threading.Dispatcher (that never returns a Task)

### ISSUE THREAD

**Issue by BionicCode** [HellBrick/HellBrick.Diagnostics#96] opened 2018-06-05 09:59 UTC
When invoking the `System.Windows.Threading.Dispatcher` the analyzer emits a warning. Because the Dispatcher object never returns a Task, the warning is rather annoying than helpful.

**Comment by HellBrick** [comment] 2018-06-05 10:05
Can you elaborate a bit? I would be helpful to see a small code sample and the warning ID so I could reproduce the problem.

**Comment by BionicCode** [comment] 2018-06-05 10:13
No problem. For instance `await Application.Current.Dispatcher.InvokeAsync(OnMergeCompleted, DispatcherPriority.Background);` generates a warning: Possibily missing 'ConfigureAwait(false)' call. The ID is just CongigureAwaitChecker. The reason for this, that the Dispatcher object doesn't return a `Task ` object but the method `ConfigureAwait(bool)` is a member of `Task`.

**Comment by HellBrick** [comment] 2018-06-05 10:30
Which version of the analyzer package are you using? This looks like a bug that was fixed recently (in 3.0.0, I think), and I indeed fail to reproduce it when referencing 3.0.2.

**Comment by BionicCode** [comment] 2018-06-05 11:16
3.0.2? Ah. I fetched it via nuget and it claims to be the latest version v1.0.1.

**Comment by HellBrick** [comment] 2018-06-05 11:19
That's weird, because the current version up on Nuget is [3.0.2](https://www.nuget.org/packages/HellBrick.Diagnostics/3.0.2) =)

Anyway, I'll close the issue now, since the bug has already been resolved.

**Closed by HellBrick** 2018-06-05 11:19 UTC
